[build]
  functions = "functions"
  base = "/"
  publish = "dist"  # Directory to publish (if applicable, for static files)
  command = "npm run build"

[functions]
  directory = "functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200